import java_cup.runtime.*;

parser code {:
:};

terminal BOOL, ELSE, IF, INT, RETURN, VOID, WHILE, TRUTH;
terminal LESSEQUAL, GREATEQUAL, EQ, NOTEQUAL, OR, AND, LESSTHAN, GREATTHAN;
terminal PLUS, MINUS, TIMES, DIVIDE, NOT;
terminal ASSIGN, SEMICOLON, COMMA;
terminal LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE;
terminal ID, NUM;

non terminal program;

start with program;

program ::= 
    /* empty */
    ;