
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int AND = 15;
  public static final int LT = 16;
  public static final int NE = 13;
  public static final int ELSE = 3;
  public static final int PLUS = 18;
  public static final int TRUTH = 9;
  public static final int RBRACE = 31;
  public static final int RPAREN = 27;
  public static final int OR = 14;
  public static final int INT = 5;
  public static final int SEMI = 24;
  public static final int WHILE = 8;
  public static final int NOT = 22;
  public static final int RETURN = 6;
  public static final int IF = 4;
  public static final int LBRACE = 30;
  public static final int LBRACKET = 28;
  public static final int LPAREN = 26;
  public static final int GT = 17;
  public static final int ID = 32;
  public static final int LE = 10;
  public static final int RBRACKET = 29;
  public static final int NUM = 33;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int DIVIDE = 21;
  public static final int MINUS = 19;
  public static final int GE = 11;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int EQ = 12;
  public static final int BOOL = 2;
  public static final int VOID = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "TRUTH",
  "LE",
  "GE",
  "EQ",
  "NE",
  "OR",
  "AND",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "ID",
  "NUM"
  };
}

